# Generated by Django 2.2.16 on 2021-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201230_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], to='products.Products'),
        ),
    ]
