# Generated by Django 2.2.16 on 2021-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210101_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='remove_order',
            field=models.BooleanField(default=False),
        ),
    ]
