# Generated by Django 2.2.16 on 2021-01-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210102_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdateView',
        ),
    ]
