# Generated by Django 2.2.16 on 2021-01-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderupdateview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdateView',
        ),
    ]
