# Generated by Django 2.2.16 on 2021-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_orderupdateview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsQuantInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='remove_order',
        ),
    ]
