# Generated by Django 2.2.16 on 2021-01-03 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210103_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='order',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='product',
            field=models.OneToOneField(null=True , blank=True , on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
            
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], to='products.ProductQuantity'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
