# Generated by Django 2.2.16 on 2021-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_productquantity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], to='products.Products'),
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
    ]
