# Generated by Django 2.2.16 on 2021-01-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210103_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], to='products.Products'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
