# Generated by Django 2.2.16 on 2021-01-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
