# Generated by Django 2.2.16 on 2021-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210105_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_pics'),
        ),
    ]
